### ISSUE TITLE
Ferdigstille fagstoff som skal brukes fram til høstferien

### ISSUE THREAD

**Issue by bitjungle** [fagstoff/ProgMod#12]
Notebooks som må ferdigstilles:

* Hello World!
* Variabler
* Kontrollstrukturer
* NumPy og andre spesialfunksjoner
* Funksjoner
* Lag et enkelt spill

**Comment by bitjungle** [comment]
Spill-fagstoff (inkludert prosjektoppgave) er ferdig.

**Comment by fuzzbin** [comment]
helloWorld, variabler, kontrollstrukturer er i hovedsak ferdig. Kom gjerne med innspill @bitjungle

**Comment by bitjungle** [comment]
Jeg mener at helloWorld, variabler og kontrollstrukturer er ferdige nok nå. Har fylt på litt i funksjoner også, men bør nok ha litt til. 

Har gjennomført layout på de fire nevnte filene. Den er sånn:

* Tittel
* opphavsrettsinfo
* &lt;hr/&gt;
* bilde/illustrasjon som flyter til høyre
* ingress (fet skift)
* referanse til kompetansemål (formattert med blockquote markdown: > )
* resten av innholdet

**Comment by bitjungle** [comment]
Fortsatt behov for finpuss og påfyll av stoff, men ferdig nok til at det kan brukes nå. Lukker denne saken.

**Comment by fuzzbin** [comment]
Supert! Da finpusser vi litt der vi kan. Kanskje lage noen flere prosjektoppgaver. 

Da løfter vi blikket og ser på modellering. :-)
