### ISSUE TITLE
Nye oppgaver til optimaliserings-fagside

### ISSUE THREAD

**Issue by bitjungle** [fagstoff/ProgMod#14]
Vi trenger et par nye oppgaver til https://github.com/fagstoff/ProgMod/blob/master/Fagstoff/optimalisering_1.ipynb 

Gjerne litt enklere enn den oppgaven som er der nå.

**Comment by bitjungle** [comment]
Har laga en oppgave, trenger en til.

**Comment by fuzzbin** [comment]
La til en oppgave. Mest for å teste utvikling der ulike personer jobber på ulike brancher som så innlemmes i master etter peer-review.

https://github.com/fagstoff/ProgMod/blob/Notebook-optimalisering-Testbranch/Fagstoff/optimalisering_1.ipynb

**Comment by fuzzbin** [comment]
Lukker denne. Branchen er merget.
