### ISSUE TITLE
Slå sammen fagstoff

### ISSUE THREAD

**Issue by fuzzbin** [fagstoff/ProgMod#22]
Bør [luftmotstand](https://github.com/fagstoff/ProgMod/blob/master/Fagstoff/luftmotstand.ipynb) rett og slett bli en del av [enkle diferensiallikninger](https://github.com/fagstoff/ProgMod/blob/master/Fagstoff/enkle%20differensiallikninger.ipynb)

Det er jo samme eksempel.

**Comment by fuzzbin** [comment]
Kan noen lese over og godkjenne før vi lukker denne?

**Comment by fuzzbin** [comment]
@bitjungle Sjekker du denne og lukker når du har tid?

**Comment by bitjungle** [comment]
Vi må tenke igjennom hva vi trenger og i hvilken sekvens de bør jobbes med av elevene:
* enkle diff.likninger
* luftmotstand
* tankmodell 2
* euler

**Comment by bitjungle** [comment]
Vent litt @fuzzbin , hvor er luftmotstand?

**Comment by fuzzbin** [comment]
Den er innlemmet i fagteksten enkle diff.likninger.

**Comment by fuzzbin** [comment]
Forslag:
1. Deler av enkle difflikninger flyttes/integreres til tankmodell 2. (Gjerne som oppgaver)
2. Ny fremdriftsplan blir: Euler -> Tankmodell2 ->Tankmodell3 osv

Jeg tenker at det hele blir mer ryddig samtidig som vi få fokus på modellering og ikke så mye på teori rundt difflikninger. Enig?

**Comment by fuzzbin** [comment]
<img width="399" alt="skjermbilde 2018-01-30 kl 21 42 46" src="https://user-images.githubusercontent.com/4933606/35590254-8e402e58-0606-11e8-9b4c-c73255379558.png">


Da lukker jeg denne. 👍
