### ISSUE TITLE
Overlappende fagstoffsider i repo ProgMod og Skolekoden.

### ISSUE THREAD

**Issue by fuzzbin** [fagstoff/ProgMod#33]
Noen av fagstoffsidene overlapper med fagstoffet i Skolekoden. Skal de oppdateres hver for seg, eller skal de lenkes? Hva tenker du @bitjungle ?

Dette gjelder f.eks. derivasjon.

**Comment by bitjungle** [comment]
Her er jeg faktisk litt usikker. Når det gjelder grunnleggende programmering i Python synes jeg er saken er grei. Her kan vel kanskje sidene om derviasjon og liknende ta litt ulike retninger? Tror jeg går for at vi oppdaterer hver for seg.

**Comment by fuzzbin** [comment]
Enig. Godt poeng med at innholdet der kan ta litt ulike retninger. Da lager jeg en fork på de aktuelle sidene.
