### ISSUE TITLE
QA - Stigespillet

### ISSUE THREAD

**Issue by fuzzbin** [fagstoff/ProgMod#34]
Førsteutkast av [oppgaveteksten](https://github.com/fagstoff/ProgMod/blob/master/Oppgaver/stigespill.md) er klar. Kom gjerne med innspill og forbedringer. :-) Bare å lukke issue når vi er fornøyd.

**Comment by bitjungle** [comment]
Omskrevet ingress og litt av oppgavetekst + korrektur
