### ISSUE TITLE
Bør notebook om kontrollstrukturer splittes

### ISSUE THREAD

**Issue by fuzzbin** [fagstoff/ProgMod#6]
Bør vi splitte notebooken i to deler. tester og løkker?

- [ ] Ja, det er lurt.
- [x]  Nei, det tror jeg ikke er lurt.
- [ ]  Samma for meg.

**Comment by bitjungle** [comment]
Beholder tester og løkker i samme notebook inntil videre, krangler videre før neste skoleår.
