### ISSUE TITLE
Mappa med notebooks

### ISSUE THREAD

**Issue by fuzzbin** [fagstoff/ProgMod#7]
Syntes den begynner å bli stor og uoversiktelig. Skulle vi blitt enige om en fil- og mappestruktur?

**Comment by fuzzbin** [comment]
Hva tenker du om navnestrukturen slik den er nå @bitjungle?

**Comment by bitjungle** [comment]
Er enig i motivasjonen bak behov for navnestruktur, men er litt usikker på hva bokstavene betyr. Angir de hvilket hovedområde i læreplanen de tilhører? Da bør det kanskje heller være GP (grunnleggende programmering), MM (matematiske metoder) og MO (modellering)? Men hva gjør vi med notebooks som går på tvers av hovedområder?

Et annet problem med nummerering av filene er at vi plutselig kan finne ut at vi trenger en ny notebook mellom for eksempel MM06 og MM07, det skaper masse trøbbel med mange filer som må endre navn.

Er det noe krise at filene ikke sorteres "naturlig" i mappa? Kan vi eventuelt lage under-mapper, sånn at ikke alt hives inn i en mappe (gruppe de notebooks som hører sammen, for eksempel tank-modellene). Sorteringa av filene gjør vi i form av en pent formattert framdriftsplan på wikien med lenker til de aktuelle filene. Hva sier du @fuzzbin?

**Comment by fuzzbin** [comment]
Enig. Vi navngir notebooks med en god beskrivende tittel, og strukturerer så alt innhold i årsplanen.
